name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bin/setup
      # Skip to test with Ruby HEAD because rbs-3.9.4 crashes with Ruby 3.5.0
      # ref: https://github.com/ruby/rbs/pull/2537/commits/c9389681acf10c9fdd34601e74153011919b8544
      if: matrix.ruby != 'head'
    - run: bundle exec rake
      # Skip to test with Ruby HEAD because rbs-3.9.4 crashes with Ruby 3.5.0
      # ref: https://github.com/ruby/rbs/pull/2537/commits/c9389681acf10c9fdd34601e74153011919b8544
      if: matrix.ruby != 'head'
