name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'lib/rbs_rails/version.rb'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
